# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui',
# licensing of 'main_page.ui' applies.
#
# Created: Mon May 27 20:38:58 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_main_page(object):    
        
    def setupUi(self, main_page):
        
        main_page.setObjectName("main_page")
        main_page.resize(1909, 1005)
        self.tabWidget = QtWidgets.QTabWidget(main_page)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(25)
        font.setUnderline(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtCore.Qt.OpenHandCursor)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"   border: 1px solid #3F3838;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: #3F3838;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #3F3838;\n"
"  color : #FFA800;\n"
" }\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(60, 60))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.dash_board = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(35)
        self.dash_board.setFont(font)
        self.dash_board.setStyleSheet("background : qlineargradient(x2:1, y2:1, x0:1, y0:1,\n"
"                stop:0 rgb(255,255,224), stop: 0.4 rgba(255,251,219, 40), stop:1 rgb(235,119,20));")
        self.dash_board.setObjectName("dash_board")
        self.heart_rate_widgets = QtWidgets.QWidget(self.dash_board)
        self.heart_rate_widgets.setGeometry(QtCore.QRect(180, 33, 720, 400))
        self.heart_rate_widgets.setStyleSheet("border : 2px solid black;\n"
"border-radius : 15px;\n"
"background : white;")
        self.heart_rate_widgets.setObjectName("heart_rate_widgets")
        self.heart_rate_widget = QtWidgets.QWidget(self.heart_rate_widgets)
        self.heart_rate_widget.setGeometry(QtCore.QRect(20, 2, 271, 395))
        self.heart_rate_widget.setStyleSheet("border: None;\n"
"border-radius: 15px 15px 15px 15px")
        self.heart_rate_widget.setObjectName("heart_rate_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.heart_rate_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 271, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.heart_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heart_rate_label.sizePolicy().hasHeightForWidth())
        self.heart_rate_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.heart_rate_label.setFont(font)
        self.heart_rate_label.setObjectName("heart_rate_label")
        self.verticalLayout.addWidget(self.heart_rate_label)
        self.max_heart_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.max_heart_rate_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.max_heart_rate_label.sizePolicy().hasHeightForWidth())
        self.max_heart_rate_label.setSizePolicy(sizePolicy)
        self.max_heart_rate_label.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.max_heart_rate_label.setFont(font)
        self.max_heart_rate_label.setObjectName("max_heart_rate_label")
        self.verticalLayout.addWidget(self.max_heart_rate_label)
        self.max_heart_rate_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_heart_rate_value.sizePolicy().hasHeightForWidth())
        self.max_heart_rate_value.setSizePolicy(sizePolicy)
        self.max_heart_rate_value.setMinimumSize(QtCore.QSize(0, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.max_heart_rate_value.setFont(font)
        self.max_heart_rate_value.setObjectName("max_heart_rate_value")
        self.verticalLayout.addWidget(self.max_heart_rate_value)
        self.line_1 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_1.setStyleSheet("border: 2px solid black;")
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.average_heart_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_heart_rate_label.sizePolicy().hasHeightForWidth())
        self.average_heart_rate_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.average_heart_rate_label.setFont(font)
        self.average_heart_rate_label.setObjectName("average_heart_rate_label")
        self.verticalLayout.addWidget(self.average_heart_rate_label)
        self.average_heart_rate_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_heart_rate_value.sizePolicy().hasHeightForWidth())
        self.average_heart_rate_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.average_heart_rate_value.setFont(font)
        self.average_heart_rate_value.setObjectName("average_heart_rate_value")
        self.verticalLayout.addWidget(self.average_heart_rate_value)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setStyleSheet("border: 2px solid black;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.min_heart_rate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_heart_rate_label.sizePolicy().hasHeightForWidth())
        self.min_heart_rate_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.min_heart_rate_label.setFont(font)
        self.min_heart_rate_label.setObjectName("min_heart_rate_label")
        self.verticalLayout.addWidget(self.min_heart_rate_label)
        self.min_heart_rate_value = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_heart_rate_value.sizePolicy().hasHeightForWidth())
        self.min_heart_rate_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.min_heart_rate_value.setFont(font)
        self.min_heart_rate_value.setObjectName("min_heart_rate_value")
        self.verticalLayout.addWidget(self.min_heart_rate_value)
        self.line_3 = QtWidgets.QFrame(self.heart_rate_widgets)
        self.line_3.setGeometry(QtCore.QRect(290, 0, 3, 400))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.graph_widget = QtWidgets.QWidget(self.heart_rate_widgets)
        self.graph_widget.setGeometry(QtCore.QRect(294, 10, 421, 381))
        self.graph_widget.setStyleSheet("border : None;")
        self.graph_widget.setObjectName("graph_widget")
        self.graph_label = QtWidgets.QLabel(self.graph_widget)
        self.graph_label.setGeometry(QtCore.QRect(130, 170, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.graph_label.setFont(font)
        self.graph_label.setObjectName("graph_label")
        self.steps_widgets = QtWidgets.QWidget(self.dash_board)
        self.steps_widgets.setGeometry(QtCore.QRect(1000, 33, 720, 400))
        self.steps_widgets.setStyleSheet("border : 2px solid black;\n"
"border-radius : 15px;\n"
"background : white;")
        self.steps_widgets.setObjectName("steps_widgets")
        self.step_label = QtWidgets.QLabel(self.steps_widgets)
        self.step_label.setGeometry(QtCore.QRect(60, 30, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.step_label.setFont(font)
        self.step_label.setStyleSheet("border : None;")
        self.step_label.setObjectName("step_label")
        self.step_value = QtWidgets.QLabel(self.steps_widgets)
        self.step_value.setGeometry(QtCore.QRect(250, 125, 221, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_value.sizePolicy().hasHeightForWidth())
        self.step_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(53)
        self.step_value.setFont(font)
        self.step_value.setStyleSheet("border : None;")
        self.step_value.setObjectName("step_value")
        self.label = QtWidgets.QLabel(self.steps_widgets)
        self.label.setGeometry(QtCore.QRect(430, 220, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("border : None;")
        self.label.setObjectName("label")
        self.food_widgets = QtWidgets.QWidget(self.dash_board)
        self.food_widgets.setGeometry(QtCore.QRect(180, 500, 720, 400))
        self.food_widgets.setStyleSheet("border : 2px solid black;\n"
"border-radius : 15px;\n"
"background : white;")
        self.food_widgets.setObjectName("food_widgets")
        self.food_background = QtWidgets.QLabel(self.food_widgets)
        self.food_background.setGeometry(QtCore.QRect(20, 10, 691, 381))
        self.food_background.setStyleSheet("background-image : url(\"./image/food_background_picture_small.jpg\");\n"
"\n"
"background-size: cover;\n"
"\n"
"opacity : 0.7;\n"
"\n"
"border : None;\n"
"")
        self.food_background.setText("")
        self.food_background.setAlignment(QtCore.Qt.AlignCenter)
        self.food_background.setObjectName("food_background")
        self.white_opacity_background = QtWidgets.QLabel(self.food_widgets)
        self.white_opacity_background.setGeometry(QtCore.QRect(20, 20, 691, 371))
        self.white_opacity_background.setStyleSheet("background: rgba(255,255,255 , 0.9);\n"
"border : None;\n"
"\n"
"\n"
"")
        self.white_opacity_background.setText("")
        self.white_opacity_background.setObjectName("white_opacity_background")
        self.food_label = QtWidgets.QLabel(self.food_widgets)
        self.food_label.setGeometry(QtCore.QRect(60, 30, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.food_label.setFont(font)
        self.food_label.setStyleSheet("border : None;\n"
"background : transparent;")
        self.food_label.setObjectName("food_label")
        self.sum_cal = QtWidgets.QLabel(self.food_widgets)
        self.sum_cal.setGeometry(QtCore.QRect(210, 170, 121, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sum_cal.sizePolicy().hasHeightForWidth())
        self.sum_cal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.sum_cal.setFont(font)
        self.sum_cal.setStyleSheet("border : None;\n"
"background : transparent;")
        self.sum_cal.setObjectName("sum_cal")
        self.standard_per_daily_cal = QtWidgets.QLabel(self.food_widgets)
        self.standard_per_daily_cal.setGeometry(QtCore.QRect(350, 190, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standard_per_daily_cal.sizePolicy().hasHeightForWidth())
        self.standard_per_daily_cal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(25)
        self.standard_per_daily_cal.setFont(font)
        self.standard_per_daily_cal.setStyleSheet("border : None;\n"
"background : transparent;")
        self.standard_per_daily_cal.setObjectName("standard_per_daily_cal")
        self.add_Button = QtWidgets.QPushButton(self.food_widgets)
        self.add_Button.setGeometry(QtCore.QRect(460, 30, 215, 40))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        self.add_Button.setFont(font)
        self.add_Button.setCursor(QtCore.Qt.PointingHandCursor)
        self.add_Button.setStyleSheet("color : black;\n"
"background : white;\n"
"border-radius : 20px;\n"
"\n"
"border: 2px solid black;\n"
"")
        self.add_Button.setObjectName("add_Button")
        self.quote_widgets = QtWidgets.QWidget(self.dash_board)
        self.quote_widgets.setGeometry(QtCore.QRect(1000, 500, 720, 400))
        self.quote_widgets.setStyleSheet("border : 2px solid black;\n"
"border-radius : 15px;\n"
"background : white;")
        self.quote_widgets.setObjectName("quote_widgets")
        self.tabWidget.addTab(self.dash_board, "")
        self.summary = QtWidgets.QWidget()
        self.summary.setObjectName("summary")
        self.tabWidget.addTab(self.summary, "")
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.tabWidget.addTab(self.profile, "")
        self.user_name = QtWidgets.QWidget()
        self.user_name.setObjectName("user_name")
        self.tabWidget.addTab(self.user_name, "")

        self.retranslateUi(main_page)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_page)

    def retranslateUi(self, main_page):
        main_page.setWindowTitle(QtWidgets.QApplication.translate("main_page", "Form", None, -1))
        self.heart_rate_label.setText(QtWidgets.QApplication.translate("main_page", "Heart rate", None, -1))
        self.max_heart_rate_label.setText(QtWidgets.QApplication.translate("main_page", "Max heart rate", None, -1))
        self.max_heart_rate_value.setText(QtWidgets.QApplication.translate("main_page", "126 bpm", None, -1))
        self.average_heart_rate_label.setText(QtWidgets.QApplication.translate("main_page", "Average heart rate", None, -1))
        self.average_heart_rate_value.setText(QtWidgets.QApplication.translate("main_page", "97   bpm", None, -1))
        self.min_heart_rate_label.setText(QtWidgets.QApplication.translate("main_page", "Min heart rate", None, -1))
        self.min_heart_rate_value.setText(QtWidgets.QApplication.translate("main_page", "60   bpm", None, -1))
        self.graph_label.setText(QtWidgets.QApplication.translate("main_page", "Show Graphs", None, -1))
        self.step_label.setText(QtWidgets.QApplication.translate("main_page", "Steps", None, -1))
        self.step_value.setText(QtWidgets.QApplication.translate("main_page", "5354  ", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("main_page", "Steps", None, -1))
        self.food_label.setText(QtWidgets.QApplication.translate("main_page", "Food", None, -1))
        self.sum_cal.setText(QtWidgets.QApplication.translate("main_page", "220  ", None, -1))
        self.standard_per_daily_cal.setText(QtWidgets.QApplication.translate("main_page", "/2150 cal", None, -1))
        self.add_Button.setText(QtWidgets.QApplication.translate("main_page", "Add", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dash_board), QtWidgets.QApplication.translate("main_page", "DASHBOARD     ", None, -1))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.dash_board), QtWidgets.QApplication.translate("main_page", "Your dashboard", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.summary), QtWidgets.QApplication.translate("main_page", "SUMMARY     ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile), QtWidgets.QApplication.translate("main_page", "PROFILE", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_name), QtWidgets.QApplication.translate("main_page", "                                                                    " + "ABCD" , None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_page = QtWidgets.QWidget()
    ui = Ui_main_page()
    ui.setupUi(main_page)
    main_page.show()
    sys.exit(app.exec_())

